---
- name: deploy Jenkins
  hosts: all
  become: yes

  tasks:

   # Show the inventory path
    - name: show env
      ansible.builtin.debug:
        var: ansible_inventory_sources

 # Show the inventory limit variable
    - name: show ansible_limit
      ansible.builtin.debug:
        var: ansible_limit

 # Show the play hosts
    - name: show ansible hosts
      ansible.builtin.debug:
        var: ansible_play_hosts_all

# Show the environment
    - name: Show env
      ansible.builtin.debug:
        var: ansible_env  

    - name: Get Jenkins key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add a key from a file on the Ansible server
      ansible.builtin.apt_key:
        data: "{{ lookup('ansible.builtin.file', '/usr/share/keyrings/jenkins-keyring.asc') }}"
        state: present

   # This likely is already installed. but ok to check
    - name: Install Java
      ansible.builtin.apt:
        name: 'openjdk-17-jre'
        state: present
        update_cache: true

    - name: append the Debian package repository address to the server’s sources.list
      ansible.builtin.shell:
        cmd: echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    - name: update the repo and install Jenkins
      ansible.builtin.apt:
        name: jenkins
        update_cache: yes

    - name: Start Jenkins
      ansible.builtin.shell:
        cmd: systemctl start jenkins
      register: start_jenkins

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
    - name: Show start
      ansible.builtin.debug:
        var: start_jenkins

    - name:  Get Jenkins status
      ansible.builtin.shell:
        cmd: systemctl status jenkins
      register: jenkins_status


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
    - name: Show Jenkins status
      ansible.builtin.debug:
        var: jenkins_status


