---
- hosts: localhost
  become: true
  pre_tasks:
    - name: Install Java
      package: name='openjdk-8-jre' state=latest

  vars:
    jenkins2_ssh_keys_generate: True
    jenkins2_smtp_enabled: False
  
  roles:
    - role: lean_delivery.jenkins


